# Generated by Django 4.2.1 on 2023-05-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('age', models.TextField()),
                ('resume_status', models.TextField()),
                ('excpirience_sum', models.TextField()),
                ('last_experience_link', models.TextField()),
                ('last_update', models.TextField()),
            ],
        ),
    ]
