# Generated by Django 4.2.1 on 2023-05-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0002_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='title_url',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
