# Generated by Django 4.2.1 on 2023-05-24 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobportal', '0004_resume_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('phone_number', models.TextField()),
                ('city', models.TextField()),
                ('birthday', models.DateField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10)),
                ('citizenship', models.TextField()),
                ('excpirience_sum', models.BooleanField()),
                ('title', models.TextField()),
                ('salary', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
