# Generated by Django 4.2.1 on 2023-05-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0005_resumeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10),
        ),
        migrations.AlterField(
            model_name='resumeuser',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
