# Generated by Django 4.2.1 on 2023-05-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0006_alter_resumeuser_gender_alter_resumeuser_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeuser',
            name='region',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
