# Generated by Django 4.2.1 on 2023-05-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0007_resumeuser_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeuser',
            name='description',
            field=models.TextField(default='super dev'),
            preserve_default=False,
        ),
    ]
